config/routes.rb
NotFoundCatcher::Engine.routes.draw do

  resources :roles, only: [:index, :edit, :update, :destroy]

  root to: 'roles#index'

end

##
# Appendo una rotta finale per matchare tutto quello sbagliato

Rails.application.routes.append do
  if NotFoundCatcher.enabled
    match '*path', controller: 'not_found_catcher/exceptions', action: :show, via: [:get, :post, :put, :delete]
  end
end

app/models/not_found_catcher/application_record.rb
module NotFoundCatcher
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/not_found_catcher/role.rb
module NotFoundCatcher
  class Role < ActiveType::Object

    attr_accessor :request_parser

    attribute :role, :string
    attribute :http_method, :string
    attribute :redirect, :string

    validate :check_redirect_uniqueness


    def persisted?
      true
    end

    def id
      self.request_parser.id
    end

    def save

      request_parser.role = self.role
      request_parser.method = self.http_method
      request_parser.redirect = self.redirect

      request_parser.save

    end

    delegate :destroy, to: :request_parser


    private

    def check_redirect_uniqueness
      unless self.redirect.blank?
        self.errors.add(:redirect, :not_unique) if NotFoundCatcher.request_store.find_by_redirect(self.redirect)
      end
    end

  end
end

app/controllers/not_found_catcher/application_controller.rb
module NotFoundCatcher
  class ApplicationController < NotFoundCatcher.base_admin_controller.constantize
    protect_from_forgery with: :exception
  end
end

app/controllers/not_found_catcher/exceptions_controller.rb
require 'yaml'
module NotFoundCatcher
  class ExceptionsController < NotFoundCatcher.base_catcher_controller.constantize

    def show
      raise NotFoundRouteException.new(request)
    end

  end
end

app/controllers/not_found_catcher/roles_controller.rb
module NotFoundCatcher
  class RolesController < NotFoundCatcher::ApplicationController

    before_action :load_object, only: [:edit, :update, :destroy]

    def index
      @store = NotFoundCatcher.request_store
    end

    def edit
    end

    def update
      @obj.assign_attributes(params.require(:role).permit(:role, :method, :redirect))


      respond_to do |f|

        if @obj.valid?

          @obj.save
          f.html {redirect_to root_path}
        else
          f.html {
            render :edit
          }
        end

      end

    end

    def destroy
      respond_to do |f|

        if @obj.destroy
          f.html {redirect_to root_path}
        else
          render :edit
        end

      end
    end

    private

    def load_object
      @obj = NotFoundCatcher.request_store.find(params[:id]).model
    end

  end
end

app/helpers/not_found_catcher/application_helper.rb
module NotFoundCatcher
  module ApplicationHelper
  end
end

app/views/layouts/not_found_catcher/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Not found catcher</title>
  <%= stylesheet_link_tag "not_found_catcher/application", media: "all" %>
  <%= javascript_include_tag "not_found_catcher/application" %>
  <%= csrf_meta_tags %>
</head>
<body class="not_found_catcher">

<%= yield %>

</body>
</html>

app/views/not_found_catcher/roles/edit.html.erb
<%= form_for @obj do |f| %>

  <%= f.text_field :role %>
  <%= f.text_field :http_method %>
  <%= f.text_field :redirect %>

  <%= f.submit %>

<% end %>

app/views/not_found_catcher/roles/index.html.erb
<table border="1">
  <tr>
    <th>Rule</th>
    <th>Method</th>
    <th>Redirect</th>
    <th></th>
  </tr>


  <% @store.each do |row| %>

    <tr>
      <td><%= row.role %></td>
      <td><%= row.method %></td>
      <td><%= row.redirect %></td>
      <td>
        <%= link_to 'edit', edit_role_path(row.id) %>
        <%= link_to 'destroy', role_path(row.id), method: :delete, data: {confirm: "Are you sure?"} %>
      </td>
    </tr>

  <% end %>

</table>